INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Shawshank Redemption', 'Frank Darabont', 'DRAMA', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Godfather', 'Francis Ford Coppola', 'CRIME', 1972);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Dark Knight', 'Christopher Nolan', 'ACTION', 2008);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Pulp Fiction', 'Quentin Tarantino', 'CRIME', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Schindler''s List', 'Steven Spielberg', 'DRAMA', 1993);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Forrest Gump', 'Robert Zemeckis', 'DRAMA', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Inception', 'Christopher Nolan', 'SCIENCE_FICTION', 2010);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Matrix', 'Lana Wachowski', 'SCIENCE_FICTION', 1999);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Silence of the Lambs', 'Jonathan Demme', 'THRILLER', 1991);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Fight Club', 'David Fincher', 'DRAMA', 1999);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Titanic', 'James Cameron', 'ROMANCE', 1997);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 'FANTASY', 2001);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Shawshank Redemption', 'Frank Darabont', 'DRAMA', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Godfather: Part II', 'Francis Ford Coppola', 'CRIME', 1974);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Schindler''s List', 'Steven Spielberg', 'DRAMA', 1993);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Dark Knight Rises', 'Christopher Nolan', 'ACTION', 2012);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Shawshank Redemption', 'Frank Darabont', 'DRAMA', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Pulp Fiction', 'Quentin Tarantino', 'CRIME', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Forrest Gump', 'Robert Zemeckis', 'DRAMA', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Lord of the Rings: The Two Towers', 'Peter Jackson', 'FANTASY', 2002);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Shawshank Redemption', 'Frank Darabont', 'DRAMA', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Dark Knight', 'Christopher Nolan', 'ACTION', 2008);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Forrest Gump', 'Robert Zemeckis', 'DRAMA', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('The Godfather', 'Francis Ford Coppola', 'CRIME', 1972);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Inception', 'Christopher Nolan', 'SCIENCE_FICTION', 2010);
