INSERT INTO Movie (title, director, genre, release_year) VALUES ('El Padrino', 'Francis Ford Coppola', 'DRAMA', 1972);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Forrest Gump', 'Robert Zemeckis', 'DRAMA', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Titanic', 'James Cameron', 'DRAMA', 1997);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Avatar', 'James Cameron', 'SCIENCE_FICTION', 2009);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Matrix', 'Lana y Lilly Wachowski', 'SCIENCE_FICTION', 1999);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('El Señor de los Anillos', 'Peter Jackson', 'ADVENTURE', 2001);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Star Wars: Una Nueva Esperanza', 'George Lucas', 'SCIENCE_FICTION', 1977);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Jurassic Park', 'Steven Spielberg', 'ADVENTURE', 1993);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Harry Potter y la Piedra Filosofal', 'Chris Columbus', 'FANTASY', 2001);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('El Rey León', 'Roger Allers y Rob Minkoff', 'ANIMATION', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('La Lista de Schindler', 'Steven Spielberg', 'DRAMA', 1993);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Gladiator', 'Ridley Scott', 'DRAMA', 2000);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('El Laberinto del Fauno', 'Guillermo del Toro', 'FANTASY', 2006);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Pulp Fiction', 'Quentin Tarantino', 'DRAMA', 1994);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('El Gran Hotel Budapest', 'Wes Anderson', 'COMEDY', 2014);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Casablanca', 'Michael Curtiz', 'DRAMA', 1942);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('La La Land', 'Damien Chazelle', 'MUSIC', 2016);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('El Silencio de los Inocentes', 'Jonathan Demme', 'MYSTERY', 1991);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('El Resplandor', 'Stanley Kubrick', 'HORROR', 1980);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Volver al Futuro', 'Robert Zemeckis', 'SCIENCE_FICTION', 1985);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Indiana Jones: En Busca del Arca Perdida', 'Steven Spielberg', 'ADVENTURE', 1981);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('E.T. El Extraterrestre', 'Steven Spielberg', 'SCIENCE_FICTION', 1982);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('Los Intocables de Eliot Ness', 'Brian De Palma', 'CRIME', 1987);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('El Sexto Sentido', 'M. Night Shyamalan', 'MYSTERY', 1999);
INSERT INTO Movie (title, director, genre, release_year) VALUES ('La Vida es Bella', 'Roberto Benigni', 'DRAMA', 1997);